# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedCardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('predicated_caption', models.CharField(max_length=50)),
                ('bounding_cortdinate', models.CharField(max_length=200)),
                ('accepted_caption', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ocr_scannedcard_details',
            },
        ),
        migrations.CreateModel(
            name='ScannedCardMaster',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('card_front', models.ImageField(blank=True, null=True, upload_to='scannedcard/')),
                ('card_back', models.ImageField(blank=True, null=True, upload_to='scannedcard/')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('imei', models.CharField(blank=True, max_length=25, null=True)),
                ('locale', models.CharField(default='en', max_length=10)),
            ],
            options={
                'db_table': 'ocr_scannedcard_master',
            },
        ),
        migrations.AddField(
            model_name='scannedcarddetail',
            name='scanned_card',
            field=models.ForeignKey(db_column='scannedcard_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='scannedcard_master_id', to='ocr.ScannedCardMaster'),
        ),
    ]
