# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='accepted_caption',
            field=models.CharField(blank=True, db_column='accepted_caption', max_length=50),
        ),
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='bounding_cortdinate',
            field=models.CharField(blank=True, db_column='bounding_cortdinate', max_length=200),
        ),
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='predicated_caption',
            field=models.CharField(blank=True, db_column='predicated_caption', max_length=50),
        ),
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='text',
            field=models.CharField(db_column='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='scannedcardmaster',
            name='card_back',
            field=models.ImageField(blank=True, db_column='card_back', null=True, upload_to='scannedcard/'),
        ),
        migrations.AlterField(
            model_name='scannedcardmaster',
            name='card_front',
            field=models.ImageField(blank=True, db_column='card_front', null=True, upload_to='scannedcard/'),
        ),
        migrations.AlterField(
            model_name='scannedcardmaster',
            name='device_type',
            field=models.CharField(blank=True, db_column='device_type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scannedcardmaster',
            name='imei',
            field=models.CharField(blank=True, db_column='imei', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='scannedcardmaster',
            name='locale',
            field=models.CharField(db_column='locale', default='en', max_length=10),
        ),
    ]
