# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20161024_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='accepted_caption',
            field=models.IntegerField(choices=[(1, 'FirstName'), (2, 'LastName'), (3, 'Title'), (4, 'Designation'), (5, 'CompanyName'), (6, 'Email'), (7, 'Website'), (8, 'CellNumber'), (9, 'PhoneNumber'), (10, 'FaxNumber'), (11, 'Address'), (0, '')], db_column='accepted_caption', default=0),
        ),
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='predicated_caption',
            field=models.IntegerField(choices=[(1, 'FirstName'), (2, 'LastName'), (3, 'Title'), (4, 'Designation'), (5, 'CompanyName'), (6, 'Email'), (7, 'Website'), (8, 'CellNumber'), (9, 'PhoneNumber'), (10, 'FaxNumber'), (11, 'Address'), (0, '')], db_column='predicated_caption', default=0),
        ),
    ]
