# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import ocr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20161025_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedcarddetail',
            name='card_side',
            field=models.IntegerField(choices=[(1, 'Front'), (2, 'Back'), (0, 'Unknown')], db_column='card_side', default=0),
        ),
        migrations.AlterField(
            model_name='scannedcardmaster',
            name='card_front',
            field=models.ImageField(db_column='card_front', default=1, max_length=254, upload_to=ocr.models.scanned_card),
            preserve_default=False,
        ),
    ]
