# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_auto_20161104_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='accepted_caption',
            field=models.IntegerField(choices=[(0, 'FirstName'), (1, 'LastName'), (2, 'Title'), (16, 'Designation'), (3, 'Company'), (7, 'Email 1'), (8, 'Email 2'), (9, 'Email 3'), (10, 'Website 1'), (11, 'Website 2'), (12, 'Website 3'), (13, 'Address 1'), (14, 'Address 2'), (15, 'LinkedIn Profile'), (4, 'Phone 1'), (5, 'Phone 2'), (6, 'Phone 3')], db_column='accepted_caption', default=999),
        ),
        migrations.AlterField(
            model_name='scannedcarddetail',
            name='predicated_caption',
            field=models.IntegerField(choices=[(0, 'FirstName'), (1, 'LastName'), (2, 'Title'), (16, 'Designation'), (3, 'Company'), (7, 'Email 1'), (8, 'Email 2'), (9, 'Email 3'), (10, 'Website 1'), (11, 'Website 2'), (12, 'Website 3'), (13, 'Address 1'), (14, 'Address 2'), (15, 'LinkedIn Profile'), (4, 'Phone 1'), (5, 'Phone 2'), (6, 'Phone 3')], db_column='predicated_caption', default=999),
        ),
    ]
